[General]

ipv6 = false
prefer-ipv6 = false
bypass-system = true
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.88.99.0/24, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255/32, ::1/128, fc00::/7, fe80::/10, ff00::/8
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.0/8, localhost, *.local, *.lan, *.internal, captive.apple.com, *.ls.apple.com, swscan.apple.com, mesu.apple.com


dns-server = h3://dns.alidns.com/dns-query, https://doh.pub/dns-query

fallback-dns-server = https://1.1.1.1/dns-query, https://8.8.8.8/dns-query


dns-direct-system = false
dns-direct-fallback-proxy = true
private-ip-answer = true

hijack-dns = 8.8.8.8:53, 1.1.1.1:53, 223.5.5.5:53, 119.29.29.29:53

[Rule]

# 噪音压制与暗黑协议清洗 
# 提前丢弃毫无意义的内网广播和运营商高频探测，净化 CPU 负担
IP-CIDR,239.255.255.250/32,REJECT,no-resolve
IP-CIDR,224.0.0.0/4,REJECT,no-resolve
IP-CIDR,100.64.0.0/10,REJECT,no-resolve
DOMAIN-SUFFIX,local,REJECT

# 局域网物理阻断 
# 严禁任何本地 IP 发起远端解析请求
IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
IP-CIDR,127.0.0.0/8,DIRECT,no-resolve


# Tier 1.5: 苹果底层生态绝对直连 
# 先于第三方规则，防止被误杀或代理，保证系统推送存活与极限省电
DOMAIN-SUFFIX,push.apple.com,DIRECT
DOMAIN-SUFFIX,ess.apple.com,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,ls.apple.com,DIRECT
DOMAIN-KEYWORD,captive.apple.com,DIRECT,no-resolve

# 核心风控与金融资产脱敏
# 确保实人认证、网银等敏感操作绝对使用原生网络
DOMAIN-SUFFIX,geetest.com,DIRECT
DOMAIN-SUFFIX,dingxiang-inc.com,DIRECT
DOMAIN-SUFFIX,tongdun.cn,DIRECT
DOMAIN-SUFFIX,shumei.com,DIRECT
DOMAIN-SUFFIX,faceplusplus.com,DIRECT
DOMAIN-SUFFIX,megvii.com,DIRECT
DOMAIN-SUFFIX,sensetime.com,DIRECT
DOMAIN-SUFFIX,unionpay.com,DIRECT
DOMAIN-SUFFIX,95516.com,DIRECT
DOMAIN-SUFFIX,alipay.com,DIRECT
DOMAIN-SUFFIX,chinaums.com,DIRECT
DOMAIN-SUFFIX,gov.cn,DIRECT

# 关键基础设施 ASN 与骨干网硬路由 
# 大厂核心 IP 段强制不解析直连
IP-CIDR,119.29.0.0/16,DIRECT,no-resolve
IP-CIDR,106.11.0.0/16,DIRECT,no-resolve
IP-CIDR,110.249.0.0/16,DIRECT,no-resolve
IP-CIDR,14.215.0.0/16,DIRECT,no-resolve
IP-CIDR,101.231.0.0/16,DIRECT,no-resolve

# 大陆环境常规应用路由 (Background Regional Ruleset)
# 引入 Blackmatrix7 社群自发秩序，处理数万级繁杂国内域名
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/China/China.list,DIRECT

# 最终地理位置锚定与兜底 
GEOIP,CN,DIRECT
FINAL,PROXY

[Host]
# 修复本地回环
localhost = 127.0.0.1
